### ISSUE TITLE
Producing an DSL version

### ISSUE THREAD

**Issue by jiang-qian** [latin-dict/Lewis1890#1]
Dear Developer,
Thank you for making this Elementary Lewis & Scott! Unfortunately the dsl version of the library on dadako website
http://dadako.narod.ru/GoldenDict/Lewis1890_lat-eng.zip
is no longer available. (It shows page not found)
Would it be possible to produce an DSL version? I tried to convert it with pyglossary, but there are many html tags that makes it hard to produce dsl. 

Also, whenever I tried to download the "source" of a dictionary, whether .zip or .tar.gz, why do I always get empty archive?

Again, I thank you for producing all these Latin dictionaries!

**Comment by jiang-qian** [comment]
Is there a program that transform dictionaries in the other format into DSL? I asked pyglossary's author by he or she refused to implement a DSL output filter.

**Comment by nikita-moor** [comment]
> Unfortunately the dsl version of the library on dadako website is no longer available. 

I have informed the admin of [dadako.narod.ru](http://dadako.narod.ru/paperpoe.htm). Hope, he fixes the problem soon.

> Also, whenever I tried to download the "source" of a dictionary, whether .zip or .tar.gz, why do I always get empty archive?

My repository is empty. The source in TEI format is [here](https://github.com/PerseusDL/lexica/tree/master/CTS_XML_TEI/perseus/pdllex/lat/ls).

> Is there a program that transform dictionaries in the other format into DSL?

No, because transformation `HTML > DSL` is not straightforward.

**Comment by jiang-qian** [comment]
OK Thank you for letting me know. I hope the DSL version will come back online. I just find DSL so easy to edit. For example, if I need to change the color of some entry, I could simply use awk to do it. For stardict or slob, I have to convert them to some kind of text, using pyglossary, and make changes and then convert back. The conversion back and forth is is far from foolproof and often introduces problems.

**Comment by jiang-qian** [comment]
How did you convert the TEI source to the stardict format? Is it possible to share the script?

**Comment by nikita-moor** [comment]
The [link](http://dadako.narod.ru/GoldenDict/Lewis1890_lat-eng.zip) works now, so I close the issue.

> How did you convert the TEI source to the stardict format? Is it possible to share the script?

I don't have time to polish the code to make it public. But remind me, please, to update this dictionary because theta (θ) is incorrect in Greek words.

**Comment by jiang-qian** [comment]
Thank you for looking into this. Unfortunately the download from the site, now linked here
http://dadako.narod.ru/GoldenDict/Lewis1890_lat-eng.zip
is in slob format, not dsl format, though different from your dictionary.
However, I understand that your time is limited, so I will not presse this issue and reopen it.

For converting TEI to dictionary format, I understand that you had no time cleaning up the code. I simply would like to propose that even imperfect code could serve as basis upon which others could build on.

Thank you again for making all these dictionaries!

**Comment by nikita-moor** [comment]
I didn't check it, sorry. And I have to express my deepest apologies to misguide you and other users because EdwART didn't make DSL versions of my dictionaries but simply copied them into their collection (in Slob format).

Though, EdwART have published recently DSL version of "big" Lewis & Short:

* [Lewis & Short Latin Dictionary, 1879. (Lat-Eng)](http://dadako.narod.ru/GoldenDict/lat-eng_Lewis-Short_v1_1-GD.7z)

An Elementary Latin Dictionary could be expected in the near future.

**Comment by jiang-qian** [comment]
Thank you for going above and beyond to help me! 

The DSL of the full Lewis & Short works! I very much look forward to the Elementary version! Sometimes the full dictionary is just a bit too overwhelming.

By the way, I sent a message to your  mail.ru email on Jan. 28/29, which may contains information of interest to you. 

I am very appreciative of EdwART's work on dictionaries! If he is comfortable in communicating in English, would it be possible for me to be directly in contact with him? That would save you a lot of troubles as intermediaries! Perhaps he could teach me how to convert dictionaries to DSL so that I don't need to bother him, either!

If that's possible, you can email me the way to contact him. If not, I would entirely understand, too!

Again, thank you for your invaluable works!

**Comment by nikita-moor** [comment]
EdwART has made DSL version of Lewis:
http://dadako.narod.ru/GoldenDict/lat-eng_Lewis-Elementary_v1_0.zip

**Comment by jiang-qian** [comment]
This dictionary works wonderfully! Thank you for making this happen!

Best Regards
Jiang
